stages:
- name: echo1
  steps:
  - runScriptConfig:
      image: harbor.eastasia.cloudapp.azure.com/library/ubuntu:16.0.4
      shellScript: echo "helloword"
timeout: 60
notification:
  recipients:
  - recipient: xiaojin
    notifier: c-n5tmm:n-55zzt
  condition:
  - Success
